## NumPy

Notebook created: 2018-03-20 23:51:37  
Generated from: _build_py/py/numpy.rst  

NumPy provides an array data type and array processing / arithmetic operations.

A Python front end to fast compiled code written in C & Fortran

In [1]:
import numpy as np

a = np.zeros(3)
a

array([0., 0., 0.])

In [2]:
type(a)

numpy.ndarray

Importantly, all elements of the array must be of the same type

In [4]:
[type(a_element) for a_element in a]

[numpy.float64, numpy.float64, numpy.float64]

In [28]:
a = np.zeros(3, dtype=np.int)
[type(a_element) for a_element in a]

[numpy.int64, numpy.int64, numpy.int64]

In [29]:
a.dtype

dtype('int64')

By construction, one dimensional NumPy arrays are **flat**

In [15]:
z = np.zeros(10)

In [16]:
z.shape

(10,)

Although we can transform them into "column vectors" and "row vectors" if we wish:

In [17]:
z.shape = (10, 1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

We can use the shape attribute to transform more generally:

In [18]:
z = np.zeros(4)
z.shape = (2, 2)
z

array([[0., 0.],
       [0., 0.]])

#### Building arrays

In [20]:
z = np.empty(3)
z

array([0., 0., 0.])

In [21]:
z = np.linspace(2, 4, 5)  # From 2 to 4, with 5 elements

In [22]:
z = np.identity(2)
z

array([[1., 0.],
       [0., 1.]])

We can build arrays from lists and tuples, like so:

In [24]:
z = np.array([10, 20])

In [25]:
type(z)

numpy.ndarray

In [26]:
z = np.array((10, 20), dtype=float)
z

array([10., 20.])

2D array from list of lists:

In [31]:
z = np.array([[1, 2], [3, 4]]) 
z

array([[1, 2],
       [3, 4]])

#### Indexing

In [30]:
z = np.linspace(1, 2, 5)

z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [31]:
z[0]

1.0

In [32]:
z[0:2]  # Two elements, starting at element 0

array([1.  , 1.25])

In [33]:
z[-1]

2.0

In [34]:
z = np.array([[1, 2], [3, 4]])
z

array([[1, 2],
       [3, 4]])

In [35]:
z[0, 1]

2

Selecting rows and columns:

In [36]:
z[0, :]

array([1, 2])

In [37]:
z[:, 1]

array([2, 4])

#### Boolean indices

In [38]:
z = np.linspace(2, 4, 5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [39]:
d = np.array([0, 1, 1, 0, 0], dtype=bool)
d

array([False,  True,  True, False, False])

In [40]:
z[d]

array([2.5, 3. ])

In [41]:
z = np.empty(3)
z

array([0.00000000e+000, 1.97345609e-312, 2.12199580e-314])

In [42]:
z[:] = 42
z

array([42., 42., 42.])

### NumPy array methods

In [43]:
a = np.array((4, 3, 2, 1))
a

array([4, 3, 2, 1])

In [44]:
a.sort()              # Sorts a in place
a

array([1, 2, 3, 4])

In [45]:
a.sum()               # Sum

10

In [46]:
a.mean()              # Mean

2.5

In [47]:
a.max()               # Max

4

In [48]:
a.argmax()            # Returns the index of the maximal element

3

In [49]:
a.cumsum()            # Cumulative sum of the elements of A

array([ 1,  3,  6, 10])

In [50]:
a.var()               # Variance

1.25

In [51]:
a.std()               # Standard deviation

1.118033988749895

In [53]:
a.shape = (2, 2)
a.T                   # Equivalent to a.transpose()

array([[1, 3],
       [2, 4]])

Another useful method is `searchsorted`

In [54]:
z = np.linspace(2, 4, 5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [58]:
z.searchsorted(2.5)

1

#### Corresponding functions in NumPy namespace

In [90]:
a = np.array((4, 3, 2, 1))

In [91]:
np.sum(a)

10

In [92]:
np.mean(a)

2.5

### Arithmetic operations

Standard arithmetic operators act **elementwise** on arrays:

In [95]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a + b

array([ 6,  8, 10, 12])

In [96]:
a * b

array([ 5, 12, 21, 32])

In [97]:
a + 10

array([11, 12, 13, 14])

In [98]:
a * 10

array([10, 20, 30, 40])

In [99]:
A = np.ones((2, 2))
B = np.ones((2, 2))
A + B

array([[2., 2.],
       [2., 2.]])

In [100]:
A + 10

array([[11., 11.],
       [11., 11.]])

In [101]:
A * B

array([[1., 1.],
       [1., 1.]])

As you can see, `*` is *not* matrix multiplication.

Here's how you do it:

In [102]:
A = np.ones((2, 2))
B = np.ones((2, 2))
A @ B

array([[2., 2.],
       [2., 2.]])

In [103]:
A = np.array((1, 2))
B = np.array((10, 20))
A @ B

50

### Implications of mutability

In [59]:
a = np.random.randn(3)
a

array([ 1.16751367, -1.36936422,  1.54547129])

The next statement binds `b` to the same object

In [60]:
b = a

Now changing `b` mutates the data that `a` points to

In [61]:
b[0] = 0.0
a

array([ 0.        , -1.36936422,  1.54547129])

In [62]:
a is b

True

This is sensible behavior!

How to make a separate copy when you need to

In [66]:
a = np.random.randn(3)
a

array([-0.78689399,  0.07501543, -1.9004477 ])

In [71]:
b = np.empty_like(a)  
np.copyto(b, a)  
b

array([-0.78689399,  0.07501543, -1.9004477 ])

In [72]:
a is b

False

In [73]:
b[:] = 1
b

array([1., 1., 1.])

In [74]:
a

array([-0.78689399,  0.07501543, -1.9004477 ])

### Ufuncs

Scalar functions (`sin`, `log`, `exp`, etc.) act individually on scalars and elementwise on arrays

In [75]:
np.sin(1)

0.8414709848078965

In [76]:
z = np.array([1, 2, 3])
np.sin(z)

array([0.84147098, 0.90929743, 0.14112001])

In [77]:
(1 / np.sqrt(2 * np.pi)) * np.exp(- 0.5 * z**2)

array([0.24197072, 0.05399097, 0.00443185])

### Comparisons

Comparisons act element by element

In [78]:
z = np.array([2, 3])
y = np.array([2, 3])
z == y

array([ True,  True])

In [79]:
y[0] = 5
z == y

array([False,  True])

In [80]:
z != y

array([ True, False])

#### Conditional extraction

In [81]:
z = np.linspace(0, 10, 5)
z

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [82]:
z > 3

array([False, False,  True,  True,  True])

In [83]:
z[z > 3]

array([ 5. ,  7.5, 10. ])

### Subpackages

The `random` subpackage:

In [84]:
z = np.random.randn(5)

In [85]:
y = np.random.binomial(10, 0.5, size=1000) 
y.mean()

4.945

Linear algebra:

In [88]:
A = np.array([[1, 2], [3, 4]])

np.linalg.det(A)           # Compute the determinant

-2.0000000000000004

In [89]:
np.linalg.inv(A)           # Compute the inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Note that SciPy has a `linalg` subpackage that is more complete.  We'll learn about it soon...